WRITE I_CABECALHO-CHAVE TO G_CHAVE USING EDIT MASK
'____ ____ ____ ____ ____ ____ ____ ____ ____ ____ ____'.

WRITE I_CABECALHO-DATA_AUT TO G_DATA_AUT USING EDIT MASK
'__/__/____'.

WRITE I_CABECALHO-HORA_AUT TO G_HORA_AUT USING EDIT MASK
'__:__:__'.



WRITE I_CABECALHO-IMP_VALNOTA         TO G_VLR_TOTAL_NF.
WRITE I_CABECALHO-IMP_VALIPI          TO G_VLR_IPI.
WRITE I_CABECALHO-IMP_OUTROS          TO G_VLR_OUTROS.
WRITE I_CABECALHO-IMP_DESCONTO        TO G_VLR_DESCONTO.
WRITE I_CABECALHO-IMP_VALSEGURO       TO G_VLR_SEGURO.
WRITE I_CABECALHO-IMP_VALFRETE        TO G_VLR_FRETE.
WRITE I_CABECALHO-IMP_VALTOT          TO G_VLR_TOT_PROD.
WRITE I_CABECALHO-IMP_VALORICMSSUBST  TO G_VLR_ICMS_SUB.
WRITE I_CABECALHO-IMP_BASEICMSSUBST   TO G_VLR_BASEICMS_SUB.
WRITE I_CABECALHO-IMP_VALICMS         TO G_VLR_ICMS.
WRITE I_CABECALHO-IMP_BASEICMS        TO G_VLR_BASEICMS.


WRITE I_CABECALHO-TRANS_PESOLIQUIDO   TO G_TRANS_PESOLIQUIDO.
WRITE I_CABECALHO-TRANS_PESOBRUTO     TO G_TRANS_PESOBRUTO.
WRITE I_CABECALHO-TRANS_QTDE          TO G_TRANS_QTDE.


WRITE I_CABECALHO-CALCISS_TOTSERV     TO G_CALCISS_TOTSERV.
WRITE I_CABECALHO-CALCISS_BASEISS     TO G_CALCISS_BASEISS.
WRITE I_CABECALHO-CALCISS_TOTISS      TO G_CALCISS_TOTISS.



















