FUNCTION ZESZBRNFE_DANFE.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_XML) TYPE  STRING
*"     REFERENCE(I_CONTROL_PARAMETERS) TYPE  SSFCTRLOP OPTIONAL
*"     REFERENCE(I_OUTPUT_OPTIONS) TYPE  SSFCOMPOP OPTIONAL
*"     REFERENCE(I_VALIDA) DEFAULT 'X'
*"  EXPORTING
*"     REFERENCE(E_DOCUMENT_OUTPUT_INFO) TYPE  SSFCRESPD
*"     REFERENCE(E_JOB_OUTPUT_INFO) TYPE  SSFCRESCL
*"     REFERENCE(E_JOB_OUTPUT_OPTIONS) TYPE  SSFCRESOP
*"  EXCEPTIONS
*"      NFE_NAO_APROVADA
*"----------------------------------------------------------------------

  DATA: T_ELEMENT_ARRAY TYPE ZDE_ELEMENT_ARRAY_T.

  CLEAR: WG_XML_SEFAZ, T_ELEMENT_ARRAY[].

  APPEND 'det' TO T_ELEMENT_ARRAY.
  APPEND 'detPag' TO T_ELEMENT_ARRAY.
  APPEND 'NFref' TO T_ELEMENT_ARRAY.
  APPEND 'DI' TO T_ELEMENT_ARRAY.
  APPEND 'adi' TO T_ELEMENT_ARRAY.
  APPEND 'detExport' TO T_ELEMENT_ARRAY.
  APPEND 'med' TO T_ELEMENT_ARRAY.
  APPEND 'arma' TO T_ELEMENT_ARRAY.
  APPEND 'comb' TO T_ELEMENT_ARRAY.
  APPEND 'lacres' TO T_ELEMENT_ARRAY.
  APPEND 'dup' TO T_ELEMENT_ARRAY.
  APPEND 'pag' TO T_ELEMENT_ARRAY.
  APPEND 'procRef' TO T_ELEMENT_ARRAY.
  APPEND 'obsCont' TO T_ELEMENT_ARRAY.
  APPEND 'obsFisco' TO T_ELEMENT_ARRAY.
  APPEND 'vol'      TO T_ELEMENT_ARRAY.

  DATA(_JSON) = ZCL_STRING=>XML_TO_JSON( I_XML           =  I_XML
                                         I_ELEMENT_ARRAY =  T_ELEMENT_ARRAY ).

  CALL METHOD /UI2/CL_JSON=>DESERIALIZE
    EXPORTING
      JSON = _JSON
    CHANGING
      DATA = WG_XML_SEFAZ.


  CLEAR: G_CONTROL_PARAMETERS.

  G_CONTROL_PARAMETERS-NO_DIALOG = 'X'.
  G_CONTROL_PARAMETERS-DEVICE    = 'PRINTER'.
  G_CONTROL_PARAMETERS-PREVIEW   = ''.
  G_CONTROL_PARAMETERS-GETOTF    = 'X'.

  G_OUTPUT_OPTIONS          = I_OUTPUT_OPTIONS.
  G_OUTPUT_OPTIONS-TDDELETE = 'X'.

*  PERFORM zf_acumula_valores
*    TABLES t_j_1bnflin
*           t_j_1bnfstx
*           t_j_1bnfnad
*    USING  t_j_1bnfdoc
*    CHANGING t_j_1bindocdx.

  PERFORM ZF_INSERE_DADOS.

  PERFORM ZF_CHAMA_SMART_FORM
    CHANGING
      E_DOCUMENT_OUTPUT_INFO
      E_JOB_OUTPUT_INFO
      E_JOB_OUTPUT_OPTIONS.

ENDFUNCTION.
