PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZIB_CTE_DIST_FLG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZIB_CTE_DIST_FLG-TP_PROCESSO_CTE .
    FIELD ZIB_CTE_DIST_FLG-CK_FORNECEDOR .
    FIELD ZIB_CTE_DIST_FLG-CK_TOMADOR .
    FIELD ZIB_CTE_DIST_FLG-CK_CT_TRANSP_SUB.
    FIELD ZIB_CTE_DIST_FLG-CK_ENT_FIS_CTE.
    FIELD ZIB_CTE_DIST_FLG-CK_NF_TRANSP .
    FIELD ZIB_CTE_DIST_FLG-CK_CT_TRANSP .
    FIELD ZIB_CTE_DIST_FLG-CK_FATURA_VF .
    FIELD ZIB_CTE_DIST_FLG-CK_REMESSA_VL .
    FIELD ZIB_CTE_DIST_FLG-CK_DOC_TRANS_VT .
    FIELD ZIB_CTE_DIST_FLG-CK_DOC_CUSTO_VI .
    FIELD ZIB_CTE_DIST_FLG-CK_PEDIDO_VI .
    FIELD ZIB_CTE_DIST_FLG-CK_FOLHA_PAG .
    FIELD ZIB_CTE_DIST_FLG-CK_MIRO_MERC .
    FIELD ZIB_CTE_DIST_FLG-CK_MIRO_FRETE .
    FIELD ZIB_CTE_DIST_FLG-CK_PESO_ORIGEM.
    FIELD ZIB_CTE_DIST_FLG-CK_PESO_CHEGADA.
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZIB_CTE_DIST_FLG-TP_PROCESSO_CTE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
