PROCESS BEFORE OUTPUT.

  MODULE STATUS_0302.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_EXIT0301 AT EXIT-COMMAND.

  CHAIN.
    FIELD ZIB_CTE_DIST_TER-ZBVTYP.
    MODULE ALTEROU_PRIORIDADE_BANCO ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD IT_0301_VT-ZVLR_FRETE.
    MODULE ALTEROU_VALOR_FRETE ON CHAIN-REQUEST.
  ENDCHAIN.

  FIELD ZIB_CTE_DIST_TER-ZDT_VENCTO
  MODULE VERIFICAR_DATA_VENCIMENTO ON REQUEST.

  CHAIN.
    FIELD ZIB_CTE_DIST_TER-ZDT_VENCTO.
    FIELD ZIB_CTE_DIST_TER-ZBVTYP.
    FIELD ZIB_CTE_DIST_TER-MWSKZ.
    FIELD IT_0301_VT-ZVLR_FRETE.
    FIELD IT_0301_VT-PESO_ORIGEM.
    MODULE ALTEROU_INFORMACAO_FRETE ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD IT_0301_VT-PESO_CHEGADA.
    MODULE ALTEROU_PESO_CHEGADA_FRETE ON CHAIN-REQUEST.
  ENDCHAIN.


  MODULE USER_COMMAND_0302.
