PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZIB_CTE_DIST_IVA CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZIB_CTE_DIST_IVA-BUKRS .
    FIELD ZIB_CTE_DIST_IVA-SHTYP .
    FIELD ZIB_CTE_DIST_IVA-TDLNR .
    FIELD ZIB_CTE_DIST_IVA-INDUSTRY .
    FIELD ZIB_CTE_DIST_IVA-ICMS .
    FIELD ZIB_CTE_DIST_IVA-MWSKZ .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZIB_CTE_DIST_IVA-BUKRS .
    FIELD ZIB_CTE_DIST_IVA-SHTYP .
    FIELD ZIB_CTE_DIST_IVA-TDLNR .
    FIELD ZIB_CTE_DIST_IVA-INDUSTRY .
    FIELD ZIB_CTE_DIST_IVA-ICMS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
