*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
INCLUDE lzescte_viagemtop.                 " Global Data
INCLUDE lzescte_viagemuxx.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
INCLUDE lzescte_viagemf00                         . " subprograms
INCLUDE lzescte_viagemi00                         . " PAI modules

*      general include-files        (never change, please)        *
INCLUDE lsvimfxx                                . " subprograms
INCLUDE lsvimoxx                                . " PBO modules
INCLUDE lsvimixx                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZESCTE_VIAGEMF...                   " Subprograms
* INCLUDE LZESCTE_VIAGEMO...                   " PBO-Modules
* INCLUDE LZESCTE_VIAGEMI...                   " PAI-Modules