*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZESCTE_VIAGEMTOP.                 " Global Data
  INCLUDE LZESCTE_VIAGEMUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZESCTE_VIAGEMF00                         . " subprograms
  INCLUDE LZESCTE_VIAGEMI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZESCTE_VIAGEMF...                   " Subprograms
* INCLUDE LZESCTE_VIAGEMO...                   " PBO-Modules
* INCLUDE LZESCTE_VIAGEMI...                   " PAI-Modules
