*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
INCLUDE lzescte_disttop.                   " Global Data
INCLUDE lzescte_distuxx.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
INCLUDE lzescte_distf00                           . " subprograms
INCLUDE lzescte_disti00                           . " PAI modules

*      general include-files        (never change, please)        *
INCLUDE lsvimfxx                                . " subprograms
INCLUDE lsvimoxx                                . " PBO modules
INCLUDE lsvimixx                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZESCTE_DISTF...                     " Subprograms
* INCLUDE LZESCTE_DISTO...                     " PBO-Modules
* INCLUDE LZESCTE_DISTI...                     " PAI-Modules

INCLUDE lzescte_distf01.

INCLUDE lzescte_distf02.

INCLUDE lzescte_distf03.

INCLUDE lzescte_distf04.

INCLUDE lzescte_distf05.