FUNCTION ZCTE_DIST_VIEW_APROVACAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(P_CD_APROVACAO) TYPE  ZESZDE_EST_APROVACAO
*"  EXCEPTIONS
*"      ID
*"      LANGUAGE
*"      NAME
*"      NOT_FOUND
*"      OBJECT
*"      REFERENCE_CHECK
*"      WRONG_ACCESS_TO_ARCHIVE
*"      NAO_ENCONTRADO
*"----------------------------------------------------------------------

  DATA: LC_ID          LIKE  THEAD-TDID,
        LC_NAME        LIKE  THEAD-TDNAME,
        LC_OBJECT      LIKE  THEAD-TDOBJECT,
        TL_TLINES      LIKE TLINE OCCURS 0 WITH HEADER LINE,
        WA_AUTORIZACAO TYPE ZESZIB_CTE_DIST_EAP.

  SELECT SINGLE * INTO WA_AUTORIZACAO
    FROM ZESZIB_CTE_DIST_EAP
   WHERE CD_APROVACAO EQ P_CD_APROVACAO.

  IF SY-SUBRC IS NOT INITIAL.
    MESSAGE E159 WITH P_CD_APROVACAO RAISING NAO_ENCONTRADO.
  ENDIF.

  LC_ID     = 'ZCTE'.
  LC_OBJECT = 'ZAPROVACAO'.
  CONCATENATE SY-MANDT P_CD_APROVACAO INTO LC_NAME.

  CALL FUNCTION 'READ_TEXT'
    EXPORTING
      ID                      = LC_ID
      LANGUAGE                = SY-LANGU
      NAME                    = LC_NAME
      OBJECT                  = LC_OBJECT
    TABLES
      LINES                   = TL_TLINES
    EXCEPTIONS
      ID                      = 1
      LANGUAGE                = 2
      NAME                    = 3
      NOT_FOUND               = 4
      OBJECT                  = 5
      REFERENCE_CHECK         = 6
      WRONG_ACCESS_TO_ARCHIVE = 7
      OTHERS                  = 8.

  CASE SY-SUBRC.
    WHEN 0.
      PERFORM VISUALIZAR_AUTORIZACAO TABLES TL_TLINES USING WA_AUTORIZACAO.
    WHEN 1.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING ID.
    WHEN 2.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING LANGUAGE.
    WHEN 3.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING NAME.
    WHEN 4.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING NOT_FOUND.
    WHEN 5.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING OBJECT.
    WHEN 6.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING REFERENCE_CHECK.
    WHEN 7.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING WRONG_ACCESS_TO_ARCHIVE.
    WHEN 8.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING OTHERS.
  ENDCASE.

ENDFUNCTION.
