FUNCTION ZDENQUEUE_CTE_TERCEIRO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(CHAVE) TYPE  ZDE_CHAVE_DOC_E
*"     REFERENCE(_SCOPE) DEFAULT '3'
*"     REFERENCE(_SYNCHRON) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT ' '
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE TYPE DDENQSCOPE,
        __SYNCHRON TYPE DDENQSYNC.

  __SYNCHRON = _SYNCHRON.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_ZIB_CTE_DIST_TER,
              MANDT	        TYPE SY-MANDT,
              CD_CHAVE_CTE  TYPE ZDE_CHAVE_DOC_E,
        END OF %A_ZIB_CTE_DIST_TER.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_ZIB_CTE_DIST_TER.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_ZIB_CTE_DIST_TER-MANDT.
  ENDIF.

  MOVE: CHAVE TO %A_ZIB_CTE_DIST_TER-CD_CHAVE_CTE.

* Preencher tab.bloqueio:

  __SEQTA_TAB-GNAME = 'ZIB_CTE_DIST_TER'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG  = %A_ZIB_CTE_DIST_TER.
  APPEND __SEQTA_TAB.

* Lock assigned:
  PERFORM SEND_ENQUEUE(SAPLSENA) TABLES __SEQTA_TAB USING '2' __SCOPE ' ' __SYNCHRON 'EZ_CTE_DIST_TER' _COLLECT.

ENDFUNCTION.
