FUNCTION ZCTE_DIST_AUTORIZACAO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(P_CD_CHAVE_CTE) TYPE  ZDE_CHAVE_DOC_E
*"     REFERENCE(P_TP_APROVACAO) TYPE  ZDE_TIP_APROVACAO
*"  EXPORTING
*"     REFERENCE(P_CD_APROVACAO) TYPE  ZDE_EST_APROVACAO
*"  CHANGING
*"     VALUE(P_TP_AUTORIZADO) TYPE  ZDE_TP_AUTORIZACAO OPTIONAL
*"  EXCEPTIONS
*"      ERRO
*"      CTE_FINALIZADO
*"      CTE_NAO_LOC
*"      CTE_BLOQUEADA
*"      CANCELADO
*"----------------------------------------------------------------------
  DATA: WA_CTE TYPE ZIB_CTE_DIST_TER.

  SELECT SINGLE * INTO WA_CTE
    FROM ZIB_CTE_DIST_TER
   WHERE CD_CHAVE_CTE EQ P_CD_CHAVE_CTE.

  "Verifica se a CT-e Existe
  IF SY-SUBRC IS NOT INITIAL.
    MESSAGE E001 WITH P_CD_CHAVE_CTE RAISING CTE_NAO_LOC.
  ENDIF.

  "Verifica se a CT-e Está finalizada
  IF WA_CTE-TP_PROCESSO_CTE IS INITIAL AND P_TP_APROVACAO NE '06' AND P_TP_APROVACAO NE '07' AND P_TP_APROVACAO NE '08'.
    MESSAGE E161 WITH P_CD_CHAVE_CTE RAISING CTE_NAO_LOC.
  ENDIF.

  "Verifica se a CT-e Está finalizada
  IF ( WA_CTE-CK_FINALIZADO EQ ABAP_TRUE ) AND ( P_TP_APROVACAO NE '01' ).
    MESSAGE E041 WITH P_CD_CHAVE_CTE RAISING CTE_NAO_LOC.
  ENDIF.

  "Bloqueia Registro da CT-e
  CALL FUNCTION 'ZENQUEUE_CTE_TERCEIRO'
    EXPORTING
      CHAVE          = P_CD_CHAVE_CTE
    EXCEPTIONS
      FOREIGN_LOCK   = 1
      SYSTEM_FAILURE = 2
      OTHERS         = 3.

  IF SY-SUBRC IS NOT INITIAL.
    MESSAGE ID SY-MSGID TYPE 'E' NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING CTE_BLOQUEADA.
  ENDIF.

  CLEAR: P_CD_APROVACAO.

  PERFORM AUTORIZACAO_CTE USING P_CD_CHAVE_CTE P_TP_APROVACAO CHANGING P_CD_APROVACAO P_TP_AUTORIZADO.

  CALL FUNCTION 'ZDENQUEUE_CTE_TERCEIRO'
    EXPORTING
      CHAVE = P_CD_CHAVE_CTE.

  IF P_CD_APROVACAO IS INITIAL.
    MESSAGE E160 RAISING CANCELADO.
  ENDIF.

ENDFUNCTION.
