FUNCTION ZCTE_DIST_FATURAMENTO_FERROV.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_CTE) TYPE  ZIB_CTE_DIST_TER
*"     REFERENCE(I_INDEX_ULTIMO) TYPE  I DEFAULT 1
*"  EXPORTING
*"     REFERENCE(E_ORDEM) TYPE  CHAR01
*"  CHANGING
*"     VALUE(I_INDEX) TYPE  I DEFAULT 1
*"     VALUE(I_DT_VENCIMENTO) TYPE  ZDT_VENCTO OPTIONAL
*"  EXCEPTIONS
*"      BLOQUEADO_USUARIO
*"----------------------------------------------------------------------

  CALL FUNCTION 'ZENQUEUE_CTE_TERCEIRO'
    EXPORTING
      CHAVE          = I_CTE-CD_CHAVE_CTE
    EXCEPTIONS
      FOREIGN_LOCK   = 1
      SYSTEM_FAILURE = 2
      OTHERS         = 3.

  IF SY-SUBRC IS NOT INITIAL.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING BLOQUEADO_USUARIO.
  ENDIF.

  PERFORM FATURAR_CTE_FERR USING I_CTE I_INDEX_ULTIMO  CHANGING I_INDEX I_DT_VENCIMENTO E_ORDEM.

  CALL FUNCTION 'ZDENQUEUE_CTE_TERCEIRO'
    EXPORTING
      CHAVE = I_CTE-CD_CHAVE_CTE.

ENDFUNCTION.
