*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZESCTE_DISTTOP.                   " Global Data
  INCLUDE LZESCTE_DISTUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZESCTE_DISTF00                           . " subprograms
  INCLUDE LZESCTE_DISTI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZESCTE_DISTF...                     " Subprograms
* INCLUDE LZESCTE_DISTO...                     " PBO-Modules
* INCLUDE LZESCTE_DISTI...                     " PAI-Modules

  INCLUDE LZESCTE_DISTF01.

  INCLUDE LZESCTE_DISTF02.

  INCLUDE LZESCTE_DISTF03.

  INCLUDE LZESCTE_DISTF04.

  INCLUDE LZESCTE_DISTF05.
