PROCESS BEFORE OUTPUT.

  MODULE STATUS_0304.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_0303_EXIT AT EXIT-COMMAND.

  FIELD ZIB_CTE_DIST_TER-DT_CHEGADA
  MODULE VERIFICAR_DT_CHEGADA_0304 ON REQUEST.

  FIELD ZIB_CTE_DIST_TER-ZDT_VENCTO
  MODULE VERIFICAR_DATA_VENCIMENTO_0304 ON REQUEST.

  FIELD ZIB_CTE_DIST_TER-ZBVTYP
  MODULE VERIFICAR_ZBVTYP_0304 ON REQUEST.

  FIELD ZIB_CTE_DIST_TER-MWSKZ
  MODULE VERIFICAR_MWSKZ_0304 ON REQUEST.

  CHAIN.
    FIELD ZIB_CTE_DIST_TER-ZBVTYP.
    MODULE ALTEROU_PRIORIDADE_BANCO_0304 ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZIB_CTE_DIST_TER-MWSKZ.
    FIELD ZIB_CTE_DIST_TER-ZDT_VENCTO.
    FIELD ZIB_CTE_DIST_TER-DT_CHEGADA.
    MODULE ALTEROU_INFORMACAO_FRETE_0304 ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZDE_CTE_DIST_VT_ALV-PESO_CHEGADA.
    FIELD ZDE_CTE_DIST_VT_ALV-PESO_ORIGEM.
    FIELD ZDE_CTE_DIST_VT_ALV-ZVLR_VI.
    FIELD ZDE_CTE_DIST_VT_ALV-ZVLR_FRETE.
    FIELD ZDE_CTE_DIST_VT_ALV-ZVLR_MERCADORIA.
    MODULE ALTEROU_PESO_CHEGADA_0304 ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0304.
