PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCTE_VIAGEM CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZESCTE_VIAGEM-CD_PROTOCOLO .
    FIELD ZESCTE_VIAGEM-DOCNUM .
    FIELD ZESCTE_VIAGEM-CNPJ_CONTRATANTE .
    FIELD ZESCTE_VIAGEM-ID_CONTRATANTE .
    FIELD ZESCTE_VIAGEM-ID_VIAGEM .
    FIELD ZESCTE_VIAGEM-DS_MSG .
    FIELD ZESCTE_VIAGEM-DT_SOLICITACAO .
    FIELD ZESCTE_VIAGEM-HR_SOLICITACAO .
    FIELD ZESCTE_VIAGEM-DT_RETORNO .
    FIELD ZESCTE_VIAGEM-HR_RETORNO .
    FIELD ZESCTE_VIAGEM-ST_CIOT .
    FIELD ZESCTE_VIAGEM-ST_ULTIMO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZESCTE_VIAGEM-CD_PROTOCOLO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
