PROCESS BEFORE OUTPUT.

  MODULE STATUS_1000.

  CALL SUBSCREEN: SUB1000 INCLUDING SY-REPID GB_TELA.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_1000_EXIT AT EXIT-COMMAND.

  CALL SUBSCREEN: SUB1000.

  MODULE USER_COMMAND_1000.
