FUNCTION Z_GRC_SEND_EMAIL_AUTO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_ACTTAB) TYPE  J_1BNFE_ACTIVE
*"  EXPORTING
*"     REFERENCE(CK_ENVIADO) TYPE  CHAR01
*"----------------------------------------------------------------------

  TRY .

      CHECK I_ACTTAB IS NOT INITIAL.

      CHECK I_ACTTAB-ACTION_REQU EQ 'C'.

      SELECT * INTO TABLE @DATA(IT_TVARVC_BUKRS)
        FROM TVARVC
       WHERE TYPE EQ 'S'
         AND NAME EQ 'ZSD_MB_BUKRS_EMAIL'.

      CHECK SY-SUBRC IS INITIAL.

      SELECT * INTO TABLE @DATA(IT_TVARVC_DOCTYP)
        FROM TVARVC
       WHERE TYPE EQ 'S'
         AND NAME EQ 'ZSD_MB_DOCTYP_EMAIL'.

      CHECK SY-SUBRC IS INITIAL.

      DATA: RGBUKRS TYPE RANGE OF BUKRS,
            WABUKRS LIKE LINE OF RGBUKRS.

      DATA: RGDOCTYP TYPE RANGE OF J_1BDOCTYP,
            WADOCTYP LIKE LINE OF RGDOCTYP.

      LOOP AT IT_TVARVC_BUKRS INTO DATA(WA_TVARVC_BUKRS).
        CLEAR: WABUKRS.
        WABUKRS-SIGN = WA_TVARVC_BUKRS-SIGN.
        WABUKRS-OPTION = WA_TVARVC_BUKRS-OPTI.
        WABUKRS-LOW = WA_TVARVC_BUKRS-LOW.
        WABUKRS-HIGH = WA_TVARVC_BUKRS-HIGH.
        APPEND WABUKRS TO RGBUKRS.
      ENDLOOP.

      LOOP AT IT_TVARVC_DOCTYP INTO DATA(WA_TVARVC_DOCTYP).
        CLEAR: WADOCTYP.
        WADOCTYP-SIGN = WA_TVARVC_BUKRS-SIGN.
        WADOCTYP-OPTION = WA_TVARVC_BUKRS-OPTI.
        WADOCTYP-LOW = WA_TVARVC_BUKRS-LOW.
        WADOCTYP-HIGH = WA_TVARVC_BUKRS-HIGH.
        APPEND WADOCTYP TO RGDOCTYP.
      ENDLOOP.

      SELECT SINGLE * INTO @DATA(WA_J_1BNFDOC)
        FROM J_1BNFDOC
       WHERE DOCNUM EQ @I_ACTTAB-DOCNUM
         AND BUKRS  IN @RGBUKRS
         AND DOCTYP IN @RGDOCTYP.

      CHECK SY-SUBRC IS INITIAL.

      SELECT * INTO TABLE @DATA(IT_J_1BNFLIN)
        FROM J_1BNFLIN
       WHERE DOCNUM EQ @I_ACTTAB-DOCNUM.

      CHECK SY-SUBRC IS INITIAL.

      DATA(TASK) = 'EMAIL_DANFE_XML_' && WA_J_1BNFDOC-DOCNUM.

      CALL FUNCTION 'Z_GRC_SEND_EMAIL' STARTING NEW TASK TASK
        EXPORTING
          PDOCNUM = WA_J_1BNFDOC-DOCNUM.


    CATCH CX_ROOT.

  ENDTRY.

ENDFUNCTION.
