FUNCTION Z_J_1B_NF_OBJECT_ADD.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     VALUE(OBJ_HEADER) LIKE  J_1BNFDOC STRUCTURE  J_1BNFDOC
*"  CHANGING
*"     VALUE(GBOBJ_HEADER) TYPE  ZDE_GBOBJ_HEADER OPTIONAL
*"     VALUE(GBOBJ_ITEM) TYPE  ZDE_GBOBJ_ITEM_T OPTIONAL
*"----------------------------------------------------------------------

*  READ TABLE GBOBJ_ITEM INTO DATA(WA_GBOBJ_ITEM) INDEX 1.
*
*  "Fatura do Serviço
*  SELECT SINGLE * INTO @DATA(WA_FATURA_SERVICO)
*    FROM VBRP
*   WHERE VBELN EQ @WA_GBOBJ_ITEM-REFKEY(10)
*     AND POSNR EQ @WA_GBOBJ_ITEM-REFITM.
*
*  CHECK SY-SUBRC IS INITIAL.
*
*  "Ordem de Venda
*  SELECT SINGLE * INTO @DATA(WA_ORDEM_VENDA)
*    FROM VBAK
*   WHERE VBELN EQ @WA_FATURA_SERVICO-AUBEL.
*
*  CHECK SY-SUBRC IS INITIAL.
*
*  SELECT SINGLE * INTO @DATA(P_DOC_TRANSP)
*    FROM VTTK
*   WHERE TKNUM EQ @WA_ORDEM_VENDA-TKNUM.
*
*  CHECK SY-SUBRC IS INITIAL.
*



ENDFUNCTION.
