FUNCTION Z_GRC_REGISTRA_INF_ZIB_NFE.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(I_DOCNUM) TYPE  J_1BDOCNUM
*"     REFERENCE(I_ACTIVE) TYPE  J_1BNFE_ACTIVE
*"----------------------------------------------------------------------

  DATA: WL_ZIB_NFE  TYPE ZIB_NFE,
        V_URL       TYPE STRING.

  CLEAR: WL_ZIB_NFE.

  CHECK I_DOCNUM IS NOT INITIAL.

  SELECT SINGLE *
    FROM J_1BNFDOC INTO @DATA(WL_DOC)
   WHERE DOCNUM EQ @I_DOCNUM.

  CHECK ( SY-SUBRC EQ 0 ).

  SELECT SINGLE * INTO WL_ZIB_NFE
    FROM ZIB_NFE
   WHERE DOCNUM EQ I_DOCNUM.

  IF SY-SUBRC NE 0.

    IF I_ACTIVE-CANCEL IS INITIAL.
      WL_ZIB_NFE-DATE_AUT_1 = I_ACTIVE-ACTION_DATE.
      WL_ZIB_NFE-TIME_AUT_1 = I_ACTIVE-ACTION_TIME.
      WL_ZIB_NFE-USER_AUT_1 = I_ACTIVE-ACTION_USER.
    ELSE.
      WL_ZIB_NFE-DATE_AUT_2 = I_ACTIVE-ACTION_DATE.
      WL_ZIB_NFE-TIME_AUT_2 = I_ACTIVE-ACTION_TIME.
      WL_ZIB_NFE-USER_AUT_2 = I_ACTIVE-ACTION_USER.
    ENDIF.

  ENDIF.

  IF I_ACTIVE-CANCEL IS INITIAL.

    IF WL_ZIB_NFE-DATE_RET_1 IS INITIAL.
      WL_ZIB_NFE-DATE_RET_1 = SY-DATUM.
      WL_ZIB_NFE-TIME_RET_1 = SY-UZEIT.
      WL_ZIB_NFE-USER_RET_1 = SY-UNAME.
    ENDIF.

    WL_ZIB_NFE-AUTHCOD      = I_ACTIVE-AUTHCOD.
    WL_ZIB_NFE-CODE         = I_ACTIVE-CODE.
    WL_ZIB_NFE-DOCNUM9      = I_ACTIVE-DOCNUM9.
    WL_ZIB_NFE-CDV          = I_ACTIVE-CDV.

    CALL FUNCTION 'Z_GRC_MONTA_LINK'
      EXPORTING
        I_DOCNUM     = I_DOCNUM
      IMPORTING
        E_LINK_PDF   = V_URL.

    WL_ZIB_NFE-DS_URL_DANFE = V_URL.

  ELSE.

    IF WL_ZIB_NFE-DATE_RET_2 IS INITIAL.
      WL_ZIB_NFE-DATE_RET_2 = SY-DATUM.
      WL_ZIB_NFE-TIME_RET_2 = SY-UZEIT.
      WL_ZIB_NFE-USER_RET_2 = SY-UNAME.
    ENDIF.

  ENDIF.

  WL_ZIB_NFE-DOCNUM       = I_DOCNUM.

  MODIFY ZIB_NFE FROM WL_ZIB_NFE.

ENDFUNCTION.
