*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZIB_CTE_DIST_TERTOP.              " Global Data
  INCLUDE LZIB_CTE_DIST_TERUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZIB_CTE_DIST_TERF00                    . " subprograms
  INCLUDE LZIB_CTE_DIST_TERI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZIB_CTE_DIST_TERF...              " Subprograms
* INCLUDE LZIB_CTE_DIST_TERO...              " PBO-Modules
* INCLUDE LZIB_CTE_DIST_TERI...              " PAI-Modules
