PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZESSDT_EXPORT-DOCNUM .
    FIELD ZESSDT_EXPORT-WERKS .
    FIELD ZESSDT_EXPORT-NF_RETORNO .
    FIELD ZESSDT_EXPORT-ORDEM .
    FIELD ZESSDT_EXPORT-DATA_CRIACAO .
    FIELD ZESSDT_EXPORT-QUANT .
    FIELD ZESSDT_EXPORT-VALOR_TOTAL .
    FIELD ZESSDT_EXPORT-EXPORT .
    FIELD ZESSDT_EXPORT-MATNR .
    FIELD ZESSDT_EXPORT-STATUS .
    FIELD ZESSDT_EXPORT-FINALIDADE .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZESSDT_EXPORT-DOCNUM .
    FIELD ZESSDT_EXPORT-WERKS .
  module detail_pai.
 endchain.
