*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZSDT_EXPORTTOP.                   " Global Data
  INCLUDE LZSDT_EXPORTUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZSDT_EXPORTF00                         . " subprograms
  INCLUDE LZSDT_EXPORTI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZSDT_EXPORTF...                   " Subprograms
* INCLUDE LZSDT_EXPORTO...                   " PBO-Modules
* INCLUDE LZSDT_EXPORTI...                   " PAI-Modules
