*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCTE_DISTTOP.                     " Global Data
  INCLUDE LZCTE_DISTUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCTE_DISTF00                           . " subprograms
  INCLUDE LZCTE_DISTI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCTE_DISTF...                     " Subprograms
* INCLUDE LZCTE_DISTO...                     " PBO-Modules
* INCLUDE LZCTE_DISTI...                     " PAI-Modules

  INCLUDE LZCTE_DISTF01.

  INCLUDE LZCTE_DISTF02.

  INCLUDE LZCTE_DISTF03.

  INCLUDE LZCTE_DISTF04.

  INCLUDE LZCTE_DISTF05.
