FUNCTION ZGRC_LIMPA_REF_MIRO_FISCAL .
*"--------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(INVOICEDOCNUMBER) TYPE  RE_BELNR
*"     REFERENCE(FISCALYEAR) TYPE  GJAHR
*"--------------------------------------------------------------------

  DATA: LC_REFKEY LIKE J_1BNFLIN-REFKEY.

  CHECK INVOICEDOCNUMBER IS NOT INITIAL AND
        FISCALYEAR IS NOT INITIAL.

  LC_REFKEY = INVOICEDOCNUMBER && FISCALYEAR.

  SELECT SINGLE * INTO @DATA(WA_J_1BNFLIN)
    FROM J_1BNFLIN
   WHERE REFTYP	EQ 'LI'
     AND REFKEY	EQ @LC_REFKEY.

  CHECK SY-SUBRC IS INITIAL.

  SELECT SINGLE *
    FROM ZSDT0231 INTO @DATA(LWA_0231)
   WHERE DOCNUM EQ @WA_J_1BNFLIN-DOCNUM.

  CHECK SY-SUBRC IS INITIAL.

  UPDATE J_1BNFLIN
     SET REFTYP = @SPACE,
         REFKEY = @SPACE,
         REFITM = @SPACE
   WHERE DOCNUM EQ @WA_J_1BNFLIN-DOCNUM
     AND DOCNUM NE @SPACE.

  UPDATE J_1BNFDOC
     SET BELNR = @SPACE,
         GJAHR = @SPACE
   WHERE DOCNUM EQ @WA_J_1BNFLIN-DOCNUM
     AND DOCNUM NE @SPACE.

  COMMIT WORK AND WAIT.

ENDFUNCTION.
