PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTNFE_ADD_RESP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTNFE_ADD_RESP-REGIO .
    FIELD ZTNFE_ADD_RESP-TIPO .
    FIELD ZTNFE_ADD_RESP-CNPJ .
    FIELD ZTNFE_ADD_RESP-CONTACT .
    FIELD ZTNFE_ADD_RESP-EMAIL .
    FIELD ZTNFE_ADD_RESP-PHONE .
    FIELD ZTNFE_ADD_RESP-IDCSRT .
    FIELD ZTNFE_ADD_RESP-CSRT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTNFE_ADD_RESP-REGIO .
    FIELD ZTNFE_ADD_RESP-TIPO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
