PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZESZIB_CTE_DIST_TER-CD_CHAVE_CTE .
    FIELD ZESZIB_CTE_DIST_TER-DOCNUM_CTE .
    FIELD ZESZIB_CTE_DIST_TER-CD_STATUS_DIST .
    FIELD ZESZIB_CTE_DIST_TER-DS_STATUS_DIST .
    FIELD ZESZIB_CTE_DIST_TER-CD_STATUS_SEFAZ .
    FIELD ZESZIB_CTE_DIST_TER-NUMR_CTE .
    FIELD ZESZIB_CTE_DIST_TER-NUMR_SERIE .
    FIELD ZESZIB_CTE_DIST_TER-DT_EMISSAO .
    FIELD ZESZIB_CTE_DIST_TER-HR_EMISSAO .
    FIELD ZESZIB_CTE_DIST_TER-VALOR_PRESTACAO .
    FIELD ZESZIB_CTE_DIST_TER-VALOR_RECEBER .
    FIELD ZESZIB_CTE_DIST_TER-VALOR_BASE_ICMS .
    FIELD ZESZIB_CTE_DIST_TER-VALOR_ICMS .
    FIELD ZESZIB_CTE_DIST_TER-CST_ICMS .
    FIELD ZESZIB_CTE_DIST_TER-CD_TOMADOR .
    FIELD ZESZIB_CTE_DIST_TER-DS_TOMADOR .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_TP_DOC .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_CPF .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_IE .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-REME_TP_DOC .
    FIELD ZESZIB_CTE_DIST_TER-REME_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-REME_CPF .
    FIELD ZESZIB_CTE_DIST_TER-REME_IE .
    FIELD ZESZIB_CTE_DIST_TER-REME_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-REME_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_TP_DOC .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_CPF .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_IE .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_TP_DOC .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_CPF .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_IE .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-DEST_TP_DOC .
    FIELD ZESZIB_CTE_DIST_TER-DEST_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-DEST_CPF .
    FIELD ZESZIB_CTE_DIST_TER-DEST_IE .
    FIELD ZESZIB_CTE_DIST_TER-DEST_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-DEST_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_TP_DOC .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_CPF .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_IE .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-MODELO .
    FIELD ZESZIB_CTE_DIST_TER-CD_MODAL .
    FIELD ZESZIB_CTE_DIST_TER-DS_MODAL .
    FIELD ZESZIB_CTE_DIST_TER-CD_TIPO_SERVICO .
    FIELD ZESZIB_CTE_DIST_TER-DS_TIPO_SERVICO .
    FIELD ZESZIB_CTE_DIST_TER-CD_TIPO_CTE .
    FIELD ZESZIB_CTE_DIST_TER-DS_TIPO_CTE .
    FIELD ZESZIB_CTE_DIST_TER-CD_FPAGAMENTO .
    FIELD ZESZIB_CTE_DIST_TER-DS_FPAGAMENTO .
    FIELD ZESZIB_CTE_DIST_TER-CD_FEMISSAO .
    FIELD ZESZIB_CTE_DIST_TER-DS_FEMISSAO .
    FIELD ZESZIB_CTE_DIST_TER-CD_APLICATIVO .
    FIELD ZESZIB_CTE_DIST_TER-DS_APLICATIVO .
    FIELD ZESZIB_CTE_DIST_TER-CODG_CFOP .
    FIELD ZESZIB_CTE_DIST_TER-INICIO_IBGE .
    FIELD ZESZIB_CTE_DIST_TER-INICIO_MUNI .
    FIELD ZESZIB_CTE_DIST_TER-INICIO_UF .
    FIELD ZESZIB_CTE_DIST_TER-TERMINO_IBGE .
    FIELD ZESZIB_CTE_DIST_TER-TERMINO_MUNI .
    FIELD ZESZIB_CTE_DIST_TER-TERMINO_UF .
    FIELD ZESZIB_CTE_DIST_TER-RG_LIDO_PAG_FRET .
    FIELD ZESZIB_CTE_DIST_TER-TP_PROCESSO_CTE .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZESZIB_CTE_DIST_TER-CD_CHAVE_CTE .
  module detail_pai.
 endchain.
