PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSDT_EXPORT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZESZSDT_EXPORT-DOCNUM .
    FIELD ZESZSDT_EXPORT-WERKS .
    FIELD ZESZSDT_EXPORT-NF_RETORNO .
    FIELD ZESZSDT_EXPORT-ORDEM .
    FIELD ZESZSDT_EXPORT-EXPORT .
    FIELD ZESZSDT_EXPORT-MATNR .
    FIELD ZESZSDT_EXPORT-STATUS .
    FIELD ZESZSDT_EXPORT-FINALIDADE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZESZSDT_EXPORT-DOCNUM .
    FIELD ZESZSDT_EXPORT-WERKS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
