PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZIB_CTE_DIST_TER CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZESZIB_CTE_DIST_TER-CD_CHAVE_CTE .
    FIELD ZESZIB_CTE_DIST_TER-DOCNUM_CTE .
    FIELD ZESZIB_CTE_DIST_TER-DS_STATUS_DIST .
    FIELD ZESZIB_CTE_DIST_TER-DS_TOMADOR .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_CPF .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_IE .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-EMIT_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-REME_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-REME_CPF .
    FIELD ZESZIB_CTE_DIST_TER-REME_IE .
    FIELD ZESZIB_CTE_DIST_TER-REME_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-REME_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_CPF .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_IE .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-EXPED_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_CPF .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_IE .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-RECEB_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-DEST_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-DEST_CPF .
    FIELD ZESZIB_CTE_DIST_TER-DEST_IE .
    FIELD ZESZIB_CTE_DIST_TER-DEST_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-DEST_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_CNPJ .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_CPF .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_IE .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_RSOCIAL .
    FIELD ZESZIB_CTE_DIST_TER-TOMA4_FANTASIA .
    FIELD ZESZIB_CTE_DIST_TER-DS_MODAL .
    FIELD ZESZIB_CTE_DIST_TER-DS_TIPO_SERVICO .
    FIELD ZESZIB_CTE_DIST_TER-DS_TIPO_CTE .
    FIELD ZESZIB_CTE_DIST_TER-DS_FPAGAMENTO .
    FIELD ZESZIB_CTE_DIST_TER-DS_FEMISSAO .
    FIELD ZESZIB_CTE_DIST_TER-DS_APLICATIVO .
    FIELD ZESZIB_CTE_DIST_TER-INICIO_MUNI .
    FIELD ZESZIB_CTE_DIST_TER-TERMINO_MUNI .
    FIELD ZESZIB_CTE_DIST_TER-P_EMISSOR .
    FIELD ZESZIB_CTE_DIST_TER-DOCNUM_CTE_C .
    FIELD ZESZIB_CTE_DIST_TER-DOCNUM_CTE_A .
    FIELD ZESZIB_CTE_DIST_TER-DOCNUM_CTE_S .
    FIELD ZESZIB_CTE_DIST_TER-EBELN .
    FIELD ZESZIB_CTE_DIST_TER-BELNR .
    FIELD ZESZIB_CTE_DIST_TER-DOCNUM_CTE_SUB .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZESZIB_CTE_DIST_TER-CD_CHAVE_CTE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
