PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZESZIB_CTE_DIST_FLG-TP_PROCESSO_CTE .
    FIELD ZESZIB_CTE_DIST_FLG-CK_FORNECEDOR .
    FIELD ZESZIB_CTE_DIST_FLG-CK_TOMADOR .
    FIELD ZESZIB_CTE_DIST_FLG-CK_CT_TRANSP_SUB.
    FIELD ZESZIB_CTE_DIST_FLG-CK_ENT_FIS_CTE.
    FIELD ZESZIB_CTE_DIST_FLG-CK_NF_TRANSP .
    FIELD ZESZIB_CTE_DIST_FLG-CK_CT_TRANSP .
    FIELD ZESZIB_CTE_DIST_FLG-CK_FATURA_VF .
    FIELD ZESZIB_CTE_DIST_FLG-CK_REMESSA_VL .
    FIELD ZESZIB_CTE_DIST_FLG-CK_DOC_TRANS_VT .
    FIELD ZESZIB_CTE_DIST_FLG-CK_DOC_CUSTO_VI .
    FIELD ZESZIB_CTE_DIST_FLG-CK_PEDIDO_VI .
    FIELD ZESZIB_CTE_DIST_FLG-CK_FOLHA_PAG .
    FIELD ZESZIB_CTE_DIST_FLG-CK_MIRO_MERC .
    FIELD ZESZIB_CTE_DIST_FLG-CK_MIRO_FRETE .
    FIELD ZESZIB_CTE_DIST_FLG-CK_PESO_ORIGEM.
    FIELD ZESZIB_CTE_DIST_FLG-CK_PESO_CHEGADA.
    FIELD ZESZIB_CTE_DIST_FLG-CK_AUTOM_MIRO.
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZESZIB_CTE_DIST_FLG-TP_PROCESSO_CTE .
  module detail_pai.
 endchain.
