PROCESS BEFORE OUTPUT.

  MODULE STATUS_0304.
*
PROCESS AFTER INPUT.

  MODULE USER_COMMAND_0303_EXIT AT EXIT-COMMAND.

  FIELD ZESZIB_CTE_DIST_TER-DT_CHEGADA
  MODULE VERIFICAR_DT_CHEGADA_0304 ON REQUEST.

  FIELD ZESZIB_CTE_DIST_TER-ZESZDT_VENCTO
  MODULE VERIFICAR_DATA_VENCIMENTO_0304 ON REQUEST.

  FIELD ZESZIB_CTE_DIST_TER-ZBVTYP
  MODULE VERIFICAR_ZBVTYP_0304 ON REQUEST.

  FIELD ZESZIB_CTE_DIST_TER-MWSKZ
  MODULE VERIFICAR_MWSKZ_0304 ON REQUEST.

  CHAIN.
    FIELD ZESZIB_CTE_DIST_TER-ZBVTYP.
    MODULE ALTEROU_PRIORIDADE_BANCO_0304 ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZESZIB_CTE_DIST_TER-MWSKZ.
    FIELD ZESZIB_CTE_DIST_TER-ZESZDT_VENCTO.
    FIELD ZESZIB_CTE_DIST_TER-DT_CHEGADA.
    MODULE ALTEROU_INFORMACAO_FRETE_0304 ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZESZDE_CTE_DIST_VT_ALV-PESO_CHEGADA.
    FIELD ZESZDE_CTE_DIST_VT_ALV-PESO_ORIGEM.
    FIELD ZESZDE_CTE_DIST_VT_ALV-ZVLR_VI.
    FIELD ZESZDE_CTE_DIST_VT_ALV-ZESZVLR_FRETE.
    FIELD ZESZDE_CTE_DIST_VT_ALV-ZVLR_MERCADORIA.
    MODULE ALTEROU_PESO_CHEGADA_0304 ON CHAIN-REQUEST.
  ENDCHAIN.

  MODULE USER_COMMAND_0304.
