FUNCTION ZENQUEUE_CTE_TERCEIRO.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(MODE) TYPE  ENQMODE DEFAULT 'X'
*"     REFERENCE(MANDT) TYPE  MANDT DEFAULT SY-MANDT
*"     REFERENCE(CHAVE) TYPE  ZESZDE_CHAVE_DOC_E
*"     REFERENCE(_SCOPE) DEFAULT '2'
*"     REFERENCE(_WAIT) DEFAULT SPACE
*"     REFERENCE(_COLLECT) TYPE  DDENQCOLL DEFAULT SPACE
*"  EXCEPTIONS
*"      FOREIGN_LOCK
*"      SYSTEM_FAILURE
*"----------------------------------------------------------------------

  DATA: __SEQTA_TAB TYPE SEQTA OCCURS 01 WITH HEADER LINE,
        __SCOPE     TYPE DDENQSCOPE,
        __WAIT      TYPE DDENQWAIT.

  __WAIT = _WAIT.
  __SCOPE = _SCOPE.

  DATA: BEGIN OF %A_ZIB_CTE_DIST_TER,
              MANDT         TYPE SY-MANDT,
              CD_CHAVE_CTE  TYPE ZESZDE_CHAVE_DOC_E,
        END OF %A_ZIB_CTE_DIST_TER.

  CALL 'C_ENQ_WILDCARD' ID 'HEX0' FIELD %A_ZIB_CTE_DIST_TER.

  MOVE: CHAVE TO %A_ZIB_CTE_DIST_TER-CD_CHAVE_CTE.

  IF NOT MANDT IS INITIAL.
    MOVE MANDT TO: %A_ZIB_CTE_DIST_TER-MANDT.
  ENDIF.

* Preencher tab.bloqueio:
  __SEQTA_TAB-GNAME = 'ZESZIB_CTE_DIST_TER'.
  __SEQTA_TAB-GMODE = MODE.
  __SEQTA_TAB-GARG = %A_ZIB_CTE_DIST_TER.
  APPEND __SEQTA_TAB.

* Fixar bloqueio:
  PERFORM SEND_ENQUEUE(SAPLSENA)
   TABLES __SEQTA_TAB
    USING '1' __SCOPE __WAIT ' ' 'EZ_CTE_DIST_TER' _COLLECT.

ENDFUNCTION.
