FUNCTION Z_GRC_MDFE_LOAD.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     VALUE(I_DOCNUM) TYPE  J_1BDOCNUM OPTIONAL
*"----------------------------------------------------------------------

  CLEAR: ZDE_ZSDT0237,
         ZDE_ZSDT0238,
         ZDE_ZSDT0240,
         ZDE_ZSDT0239,
         ZDE_ZSDT0242,
         GB_ZSDT0237,
         GT_ZSDT0238,
         GT_ZDE_ZSDT0238[], GT_ZDE_ZSDT0238,
         GT_ZSDT0240,
         GT_ZDE_ZSDT0240[], GT_ZDE_ZSDT0240,
         GT_ZSDT0239,
         GT_ZDE_ZSDT0239[], GT_ZDE_ZSDT0239,
         GT_ZSDT0241,
         GT_ZSDT0243,
         GT_ZSDT0242,
         GT_ZDE_ZSDT0242[], GT_ZDE_ZSDT0242,
         WA_LOCAL_DESC_SEL.

  ZDE_ZSDT0237-COUNTRY = 'BR'.

  CHECK I_DOCNUM IS NOT INITIAL.

  "Cabeçalho
  SELECT SINGLE * INTO @GB_ZSDT0237 FROM ZESZSDT0237 WHERE DOCNUM EQ @I_DOCNUM.
  "Manifesto Documento Eletrônico - Avulso - Local Carregamento
  SELECT * INTO TABLE @GT_ZSDT0238 FROM ZSDT0238 WHERE DOCNUM EQ @I_DOCNUM.
  "Manifesto Documento Eletrônico - Avulso - UF's Percurso
  SELECT * INTO TABLE @GT_ZSDT0240 FROM ZSDT0240 WHERE DOCNUM EQ @I_DOCNUM.
  "Manifesto Documento Eletrônico - Avulso - Mun Descarrega
  SELECT * INTO TABLE @GT_ZSDT0239 FROM ZSDT0239 WHERE DOCNUM EQ @I_DOCNUM.
  "Manifesto Documento Eletrônico - Avulso - Mun Descarrega Doc
  SELECT * INTO TABLE @GT_ZSDT0241 FROM ZSDT0241 WHERE DOCNUM EQ @I_DOCNUM.
  "Manifesto Documento Eletrônico - Avulso - Veículos
  SELECT * INTO TABLE @GT_ZSDT0243 FROM ZSDT0243 WHERE DOCNUM EQ @I_DOCNUM.
  "Manifesto Documento Eletrônico - Avulso - Condutores
  SELECT * INTO TABLE @GT_ZSDT0242 FROM ZSDT0242 WHERE DOCNUM EQ @I_DOCNUM.

  MOVE-CORRESPONDING GB_ZSDT0237 TO ZDE_ZSDT0237.

  PERFORM CARREGA_EMPRESA.
  PERFORM CARREGA_FILIAL.
  PERFORM CARREGA_MUNICIOPIO_ORIGEM.
  PERFORM CARREGA_MUNICIOPIO_FINAL.
  PERFORM CARREGA_PROD_PREDOMINANTE.
  PERFORM CARREGA_DOC_ELETRONICO.
  PERFORM CARREGA_LOCAL_CARREGAMENTOS.
  PERFORM CARREGA_UFS_PERCURSO.
  PERFORM CARREGA_MUN_DESCARREGAMENTOS.
  PERFORM CARREGA_CONDUTORES.

ENDFUNCTION.
