*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCTE_VIAGEMTOP.                   " Global Data
  INCLUDE LZCTE_VIAGEMUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCTE_VIAGEMF00                         . " subprograms
  INCLUDE LZCTE_VIAGEMI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCTE_VIAGEMF...                   " Subprograms
* INCLUDE LZCTE_VIAGEMO...                   " PBO-Modules
* INCLUDE LZCTE_VIAGEMI...                   " PAI-Modules
